### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by blmhds** [VisCog/ArgusShapes#9]
When I use pip to install the main package, argus_shapes, this question I have no idea to solve.
I need some help to solve this question.
Thank you very much.
This is the error:
ERROR: Invalid requirement: 'Maemi\Desktop\6\phosphene\VisCog-ArgusShapes-25440ba\argus_shapes'
It looks like a path. File 'Maemi\Desktop\6\phosphene\VisCog-ArgusShapes-25440ba\argus_shapes' does not exist.

**Comment by mbeyeler** [comment]
Hi!

There is a step that is not mentioned in the installation instructions, which is to download the source code from GitHub. I have updated the installation instructions here: https://github.com/VisCog/ArgusShapes#installation.

That should resolve your issue. If not, please let me know which command exactly fails.

Thanks,
Michael

**Comment by WuGen-star** [comment]
Helllo!

I am the user "blmhds". I have sent an e-mail to you.

Please check it.

Thanks,
Wu
